apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      kubernetes.io/ingress.class: "nginx"
  name: ingress
  namespace: default 
    "helm.sh/hook": post-install
  # "helm.sh/hook-weight": "2"
spec:
  tls:
  - hosts:
    - mateuszkdeveleap.ddns.net
    secretName: letsencrypt-tls
  - host: mateuszkdeveleap.ddns.net
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: demo-crm-service
            port:
              number: 3000